command line for claimer
eluv-io/elv-live-js pull request #63
Opened 2022-08-03 03:04 UTC by elv-Tom

2022-08-18 04:33 UTC, elv-wayne requested changes

2022-08-18 04:33 UTC, elv-wayne commented on src/ElvContracts.js
> +    for (let i ; i<lengthList; i++){
Add initializer in the for loop: let i=0;

2022-08-18 04:33 UTC, elv-wayne commented on src/ElvContracts.js
> +        listAllocations.push("amount : " + elemAmount + " - expiration : " + elemExpirationDate);
Push a new object instead:  {amount: elementAmount, expiration: elemExpirationDate}

2022-08-18 04:33 UTC, elv-wayne commented on src/ElvContracts.js
> +    return listAllocations.toString();
Just return the listAllocations

2022-08-18 04:33 UTC, elv-wayne commented on src/ElvContracts.js
> +      contractAddress: Config.consts.main.claimerAddress,
Should use command params for the contract address and not the config

2022-08-18 04:33 UTC, elv-wayne commented on utilities/EluvioCli.js
> +    let elvAccount = new ElvContracts({
rename variable to elvContracts (For the other functions as well), confusing since we have an ElvAccount class

2022-09-01 02:00 UTC, elv-serban approved these changes
Looks good - ready to go

2022-09-01 03:20 UTC, elv-wayne approved these changes
I see the claimerAddress is still in the config instead of taking it as a command param but I'll leave it to you @elv-serban to decide

2022-09-01 22:28 UTC, merged